-- generated by tools/gen_story_quests.py (T82)
if call_type == "on_cutscene_end" then
    if zone == "cutscene" then
        if story_phase == "after" then
            clear_quest(sender, 703270)
            unlock_quest(sender, 703300)
            story_reward(sender, "QueenAnt", false)
            move_lobby(sender)
        else
            story_phase = "field"
            move_player(sender, "campship_down")
        end
    end
end
