-- generated by tools/gen_story_quests.py (T82): story battle with scenes before=st_039040_om after=st_039100
if call_type == "on_map_loaded" then
    if zone == "campship" and not story_landed then
        story_landed = true
        story_phase = "before"
        move_player(sender, "cutscene")
    elseif zone == "cutscene" then
        local cutscene_data = {}
        if story_phase == "after" then
            cutscene_data.scene_name = "st_039100"
        else
            cutscene_data.scene_name = "st_039040_om"
        end
        cutscene_data.unk5 = 6
        cutscene_data.unk7 = 14
        local packet = {}
        packet.StartCutscene = cutscene_data
        send(sender,packet)
    end
end
