-- generated by tools/gen_story_quests.py (T69): story battle
if call_type == "on_quest_clear" then
    clear_quest(sender, 702810)
    unlock_quest(sender, 702820)
    story_reward(sender, "Mono0GreatEvilA", true)
end
