-- generated by tools/gen_story_quests.py (T69): story battle
if call_type == "on_quest_clear" then
    clear_quest(sender, 700035)
    unlock_quest(sender, 700040)
    story_reward(sender, "Char01_Maskman", true)
end
