-- generated by tools/gen_story_quests.py (T69): story battle
if call_type == "on_quest_clear" then
    clear_quest(sender, 701450)
    unlock_quest(sender, 701451)
    story_reward(sender, "DragonBerserkAUniq1", true)
end
