-- generated by tools/gen_story_quests.py (T82)
if call_type == "on_cutscene_end" then
    if zone == "cutscene" then
        if story_phase == "after" then
            clear_quest(sender, 701420)
            unlock_quest(sender, 701422)
            story_reward(sender, "DragonBerserkAUniq1", false)
            move_lobby(sender)
        else
            story_phase = "field"
            move_player(sender, "campship_down")
        end
    end
end
