-- generated by tools/gen_story_quests.py (T69): campship -> field once
if call_type == "on_map_loaded" then
    if zone == "campship" and not story_landed then
        story_landed = true
        move_player(sender, "campship_down")
    end
end
